name: "David Phillips - A website in 2 parts"
description: ""

url: "http://davidphillips.us"

paginate: 3

markdown: rdiscount
permalink: pretty
pygments: true

exclude: [codekit-config.json, Gemfile, Gemfile.lock, foundation.gemspec, package.json, Rakefile, README.md, docs, scss, templates]